name: checkmake action

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: write

jobs:
  checkmake:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
        with:
          submodules: true
      - name: checkmake action
        uses: Uno-Takashi/checkmake-action@main
